### ISSUE TITLE
Add an option to enable/disable `alignedSeqQC` in workflow

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo-workflows/rna-seq-alignment#29]
Since QC WG will create dedicated post-alignment-wf to QC all aligned seq, we can add an option into the workflow to enable/disable the step of `alignedSeqQC`.

**Comment by lindaxiang** [comment]
https://github.com/icgc-argo-workflows/rna-seq-alignment/pull/34

**Comment by b-f-chan** [comment]
Since this is addressed, closing
